# Generated by Django 4.0.4 on 2023-05-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=80)),
                ('marca', models.CharField(max_length=80)),
                ('descripcion', models.TextField()),
                ('imagen', models.CharField(max_length=250)),
            ],
        ),
    ]
