# Generated by Django 4.2.1 on 2023-05-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='profile_default.jpg', upload_to='users/'),
        ),
    ]
