# Generated by Django 4.0.4 on 2023-05-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroUsuario',
            fields=[
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('correo', models.EmailField(blank=True, max_length=254, primary_key=True, serialize=False)),
                ('telefono', models.IntegerField(default=1000)),
                ('fecha_nac', models.DateField(auto_now_add=True)),
                ('direccion', models.CharField(max_length=80)),
                ('comuna', models.CharField(max_length=80)),
                ('contraseña', models.CharField(max_length=8)),
                ('rep_contraseña', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='accesorio',
            name='precio',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='accesorio',
            name='descripcion',
            field=models.TextField(max_length=250),
        ),
    ]
