# Generated by Django 4.2.1 on 2023-05-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_producto_id_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
