# Generated by Django 4.0.4 on 2023-05-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_registrousuario_accesorio_precio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('correo', models.EmailField(blank=True, max_length=254, primary_key=True, serialize=False)),
                ('telefono', models.IntegerField(default=1000)),
                ('mesnsaje', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='LogIn',
            fields=[
                ('correo', models.EmailField(blank=True, max_length=254, primary_key=True, serialize=False)),
                ('contraseña', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='LoginAdmin',
            fields=[
                ('correo', models.EmailField(blank=True, max_length=254, primary_key=True, serialize=False)),
                ('contraseña', models.CharField(max_length=8)),
            ],
        ),
    ]
