# Generated by Django 4.2.1 on 2023-05-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_poducto', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('descripcion', models.CharField(max_length=255, null=True, unique=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('costo', models.DecimalField(decimal_places=2, max_digits=13)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=13)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'order_with_respect_to': 'descripcion',
            },
        ),
    ]
