# Generated by Django 4.0.4 on 2023-05-05 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contacto_login_loginadmin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registrousuario',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.RenameField(
            model_name='registrousuario',
            old_name='direccion',
            new_name='domicilio',
        ),
        migrations.RenameField(
            model_name='registrousuario',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.RenameField(
            model_name='registrousuario',
            old_name='contraseña',
            new_name='pwd',
        ),
        migrations.RenameField(
            model_name='registrousuario',
            old_name='rep_contraseña',
            new_name='pwd1',
        ),
    ]
