# Generated by Django 4.2.1 on 2023-05-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_producto_plataforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('Juego', 'Juego'), ('Accesorio', 'Accesorio'), ('Juego Descargable', 'Juego Descargable')], default='Juego', max_length=200),
        ),
    ]
