# Generated by Django 4.2 on 2023-05-05 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_registrousuario_formregistro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accesorio',
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
        migrations.DeleteModel(
            name='formRegistro',
        ),
        migrations.DeleteModel(
            name='LogIn',
        ),
        migrations.DeleteModel(
            name='LoginAdmin',
        ),
    ]
