# Generated by Django 4.2.1 on 2023-05-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_producto_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='id_poducto',
            new_name='id_producto',
        ),
    ]
