# Generated by Django 4.2.1 on 2023-05-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_producto_categoria_alter_producto_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='plataforma',
            field=models.CharField(choices=[('PlayStation 5', 'PlayStation 5'), ('Xbox Series X', 'Xbox Series X'), ('Nintendo Switch', 'Nintendo Switch'), ('PC Gaming', 'PC Gaming'), ('PlayStation 4', 'PlayStation 4'), ('Xbox One', 'Xbox One'), ('Nintendo 3DS', 'Nintendo 3DS'), ('Sega Genesis Mini', 'Sega Genesis Mini'), ('Super Nintendo Entertainment System (SNES) Classic Edition', 'Super Nintendo Entertainment System (SNES) Classic Edition'), ('Nintendo Entertainment System (NES) Classic Edition', 'Nintendo Entertainment System (NES) Classic Edition')], default='PlayStation 5', max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('Acción', 'Acción'), ('Aventura', 'Aventura'), ('Estrategia', 'Estrategia'), ('RPG', 'RPG'), ('Deportes', 'Deportes'), ('Carreras', 'Carreras'), ('Puzzle', 'Puzzle'), ('Plataformas', 'Plataformas'), ('Shooter', 'Shooter'), ('Simulación', 'Simulación')], default='Acción', max_length=200),
        ),
    ]
