# Generated by Django 4.2.1 on 2023-05-29 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_producto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('', '----'), ('Acción', 'Acción'), ('Aventura', 'Aventura'), ('Estrategia', 'Estrategia'), ('RPG', 'RPG'), ('Deportes', 'Deportes'), ('Carreras', 'Carreras'), ('Puzzle', 'Puzzle'), ('Plataformas', 'Plataformas'), ('Shooter', 'Shooter'), ('Simulación', 'Simulación')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='plataforma',
            field=models.CharField(choices=[('', '----'), ('PlayStation 5', 'PlayStation 5'), ('Xbox Series X', 'Xbox Series X'), ('Xbox 360', 'Xbox 360'), ('Nintendo Switch', 'Nintendo Switch'), ('PC Gaming', 'PC Gaming'), ('PlayStation 4', 'PlayStation 4'), ('Xbox One', 'Xbox One'), ('Nintendo 3DS', 'Nintendo 3DS'), ('Sega Genesis Mini', 'Sega Genesis Mini'), ('Super Nintendo Entertainment System (SNES) Classic Edition', 'Super Nintendo Entertainment System (SNES) Classic Edition'), ('Nintendo Entertainment System (NES) Classic Edition', 'Nintendo Entertainment System (NES) Classic Edition')], default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('', '----'), ('Juego', 'Juego'), ('Accesorio', 'Accesorio'), ('Juego Descargable', 'Juego Descargable')], default='', max_length=200),
        ),
    ]
