# Generated by Django 4.2.1 on 2023-05-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_id_poducto_producto_id_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.AddField(
            model_name='producto',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/productos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='users/profile_default.png', upload_to='media/users/'),
        ),
    ]
