# Generated by Django 4.2.1 on 2023-06-01 23:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=250, verbose_name='Direccion')),
                ('numero', models.CharField(max_length=250, verbose_name='Número')),
                ('descripcion', models.CharField(blank=True, max_length=250, verbose_name='Descripcion')),
                ('ciudad', models.CharField(max_length=250, verbose_name='Ciudad')),
                ('is_pagado', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Ordenes',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='core.producto')),
            ],
        ),
    ]
