# Generated by Django 3.2.4 on 2023-06-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='order',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='order',
            name='numero',
        ),
        migrations.AddField(
            model_name='order',
            name='comuna',
            field=models.CharField(max_length=250, null=True, verbose_name='Comuna'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name='Nombre completo'),
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.CharField(max_length=250, null=True, verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='order',
            name='telefono',
            field=models.CharField(max_length=250, null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='order',
            name='direccion',
            field=models.CharField(max_length=250, null=True, verbose_name='Direccion'),
        ),
    ]
