# Generated by Django 3.2.4 on 2023-06-02 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230601_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='precio',
            new_name='costo',
        ),
    ]
