# Generated by Django 3.2.4 on 2023-06-02 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_precio_item_costo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='order',
            name='descripcion',
            field=models.CharField(blank=True, max_length=250, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='order',
            name='direccion',
            field=models.CharField(max_length=250, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(max_length=250, null=True, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='order',
            name='telefono',
            field=models.CharField(max_length=250, null=True, verbose_name='Teléfono'),
        ),
    ]
