# Generated by Django 3.2.4 on 2023-06-02 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20230602_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='username',
            new_name='nombre',
        ),
    ]
