# Generated by Django 3.2.4 on 2023-06-02 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_username_order_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='costo',
            new_name='precio',
        ),
    ]
