# Generated by Django 3.2.4 on 2023-06-02 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_order_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='precio',
            new_name='costo',
        ),
    ]
