# Generated by Django 4.2.1 on 2023-06-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_precio_item_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('', '----'), ('Juego', 'Juego'), ('Accesorio', 'Accesorio'), ('Codigo Digital', 'Codigo Digital')], default='', max_length=200),
        ),
    ]
