# Generated by Django 4.2.1 on 2023-06-13 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_producto_tipo_producto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'verbose_name': 'compra', 'verbose_name_plural': 'compras'},
        ),
        migrations.RenameField(
            model_name='compra',
            old_name='id_producto',
            new_name='sku',
        ),
    ]
