# Generated by Django 4.2.1 on 2023-06-13 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_compra_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compra',
            old_name='picture',
            new_name='documento',
        ),
    ]
