# Generated by Django 3.2.4 on 2023-06-15 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_itemprovider_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemprovider',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemprovider', to='core.orden'),
        ),
    ]
