# Generated by Django 3.2.4 on 2023-06-16 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_itemprovider_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='estado_orden',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Bloqueada', 'Bloqueada'), ('Aceptada', 'Aceptada')], default='Pendiente', max_length=200, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='itemprovider',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemproviders', to='core.orden'),
        ),
    ]
