# Generated by Django 3.2.4 on 2023-06-16 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20230615_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estado_venta',
            field=models.CharField(choices=[('En Preparación', 'En Preparación'), ('En Ruta', 'En Ruta'), ('Entregado', 'Entregado')], default='En Preparación', max_length=200, verbose_name='Estado Órden'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado_orden',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Bloqueada', 'Bloqueada'), ('Aceptada', 'Aceptada')], default='Pendiente', max_length=200, verbose_name='Estado Órden'),
        ),
    ]
