# Generated by Django 3.2.4 on 2023-06-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_orden_estado_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='nfactura',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
