# Generated by Django 4.2 on 2023-05-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nombres', models.CharField(max_length=80)),
                ('apellidos', models.CharField(max_length=80)),
                ('correo', models.EmailField(blank=True, max_length=254, primary_key=True, serialize=False)),
                ('telefono', models.IntegerField(default=1000)),
                ('fecha_nac', models.DateField(auto_now_add=True)),
                ('domicilio', models.CharField(max_length=80)),
                ('comuna', models.CharField(max_length=80)),
                ('pwd', models.CharField(max_length=8)),
                ('pwd1', models.CharField(max_length=8)),
            ],
        ),
    ]
