# Generated by Django 4.2 on 2023-05-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=70)),
                ('apellidos', models.CharField(max_length=70)),
                ('correo', models.CharField(max_length=100)),
                ('pwd', models.CharField(max_length=100)),
                ('pwd1', models.CharField(max_length=100)),
                ('telefono', models.IntegerField()),
                ('fecha_nac', models.DateField()),
                ('domicilio', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=100)),
            ],
        ),
    ]
